/* eslint-disable prettier/prettier */
import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Heading from '../../shared/ui/Heading/Heading';
import Header from '../../shared/ui/Header/Header';
import Footer from '../../shared/ui/Footer/Footer';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>DAMS</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="theme-color" content="#151515" />
    </Head>
    <main>
      <div className="navbar relative z-10">
        <Header />
      </div>

      <div className="about-us flex flex-col justify-center items-center mt-10 mb-10">
        <div className="container flex flex-col justify-center items-center m-10 w-[50%]">
          <Heading
            title="Terms & Conditions"
            type="newxl"
            color="primary"
            classes="text-bordercolor font-semibold cursor-pointer"
          />

          <Heading
            title="Last updated on January 9, 2023"
            type="md"
            color="primary"
            classes="text-bordercolor font-normal pb-24"
          />

          <Heading
            title="This Terms & Conditions describes how Dams Labs Inc. Dams, we, us or our collects, protects and uses the personally identifiable information Personal Information you User, you or your may provide through the Dams UI website (Damsui.com) or in the course of purchasing any Dams UI products (collectively, Website. The Terms & Conditions also describes the choices available to you regarding our use of your Personal Information and how you can access and update this information. This Terms & Conditions does not apply to the practices of companies that we do not own or control, or to individuals that we do not employ or manage."
            type="md"
            color="primary"
            classes="text-black font-normal pb-2"
          />
        </div>

        <div className="container flex flex-col items-start mt-4 w-[50%]">
          <Heading
            title="Collection of personal information"
            type="md"
            color="primary"
            classes="text-bordercolor font-semibold pb-2"
          />
          <Heading
            title="We receive and store any information you knowingly provide to us when you make a purchase through the Website. Currently this is limited to your email address, which is required for you to be able to login to the Website and access any purchased Dams UI products."
            type="sm"
            color="primary"
            classes="text-black font-normal pb-2"
          />
        </div>

        <div className="container flex flex-col items-start mt-4 w-[50%]">
          <Heading
            title="Collection of non-personal information"
            type="md"
            color="primary"
            classes="text-bordercolor font-semibold pb-2"
          />
          <Heading
            title="We receive and store any information you knowingly provide to us when you make a purchase through the Website. Currently this is limited to your email address, which is required for you to be able to login to the Website and access any purchased Dams UI products."
            type="sm"
            color="primary"
            classes="text-black font-normal pb-2"
          />
        </div>

        <div className="container flex flex-col items-start mt-4 w-[50%]">
          <Heading
            title="Managing personal information"
            type="md"
            color="primary"
            classes="text-bordercolor font-semibold pb-2"
          />
          <Heading
            title="We receive and store any information you knowingly provide to us when you make a purchase through the Website. Currently this is limited to your email address, which is required for you to be able to login to the Website and access any purchased Dams UI products."
            type="sm"
            color="primary"
            classes="text-black font-normal pb-2"
          />
        </div>

        <div className="container flex flex-col items-start mt-4 w-[50%]">
          <Heading
            title="Use and processing of collected information"
            type="md"
            color="primary"
            classes="text-bordercolor font-semibold pb-2"
          />
          <Heading
            title="We receive and store any information you knowingly provide to us when you make a purchase through the Website. Currently this is limited to your email address, which is required for you to be able to login to the Website and access any purchased Dams UI products."
            type="sm"
            color="primary"
            classes="text-black font-normal pb-2"
          />
        </div>

        <div className="container flex flex-col items-start mt-4 w-[50%]">
          <Heading
            title="Information transfer and storage"
            type="md"
            color="primary"
            classes="text-bordercolor font-semibold pb-2"
          />
          <Heading
            title="We receive and store any information you knowingly provide to us when you make a purchase through the Website. Currently this is limited to your email address, which is required for you to be able to login to the Website and access any purchased Dams UI products."
            type="sm"
            color="primary"
            classes="text-black font-normal pb-2"
          />
        </div>

        <div className="container flex flex-col items-start mt-4 w-[50%]">
          <Heading
            title="The right to object to processing"
            type="md"
            color="primary"
            classes="text-bordercolor font-semibold pb-2"
          />
          <Heading
            title="We receive and store any information you knowingly provide to us when you make a purchase through the Website. Currently this is limited to your email address, which is required for you to be able to login to the Website and access any purchased Dams UI products."
            type="sm"
            color="primary"
            classes="text-black font-normal pb-2"
          />
        </div>
      </div>

      <div className="div">
        <Footer />
      </div>
    </main>
  </div>
);

export default Home;
