/* eslint-disable prettier/prettier */
import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Heading from '../../shared/ui/Heading/Heading';
import Header from '../../shared/ui/Header/Header';
import Footer from '../../shared/ui/Footer/Footer';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>DAMS</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="theme-color" content="#151515" />
    </Head>
    <main>
      <div className="navbar relative z-10">
        <Header />
      </div>
      <div className="about-us flex justify-center items-center h-[30vh]">
        <h1>Services</h1>
      </div>
      <div className="div">
        <Footer />
      </div>
    </main>
  </div>
);

export default Home;
