/* eslint-disable prettier/prettier */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable no-underscore-dangle */
import React, { useState, useEffect } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import moment from 'moment';
import Heading from '../../shared/ui/Heading/Heading';
import { Loader } from '../../shared/ui/Loader/Loader';
import Header from '../../shared/ui/Header/Header';
import Footer from '../../shared/ui/Footer/Footer';
import { useGetAllBlogMutation } from '../../shared/api/blogApi/blogApi';

export interface BlogData {
  _id: string | null;
  title: string;
  author: string;
  category: string;
  slug?: string;
  description: string;
  summary: string;
  main_image: string;
}

const Home: NextPage = () => {
  const [page] = useState(1);
  const [limit] = useState(10);

  const [getAllBlog, { data, isLoading }] = useGetAllBlogMutation();

  const GetData = async () => {
    try {
      await getAllBlog({
        page,
        limit,
      });
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    GetData();
  }, []);

  if (isLoading) {
    return (
      <div className="container max-w-6xl mt-12 p-6 mx-auto space-y-6 sm:space-y-12">
        <Loader />
      </div>
    );
  }

  return (
    <div>
      <Head>
        <title>DAMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content="#151515" />
      </Head>

      <main>
        <div className="navbar relative z-10">
          <Header />
        </div>

        <div className="py-24 flex-col items-center justify-center  px-4">
          <Heading
            title="Read Our Latest"
            type="newxl"
            color="primary"
            classes="text-center text-bordercolor font-bold cursor-pointer pb-2"
          />

          <Heading
            title="Whether article spirits new her covered hastily sitting her. Money witty books nor son"
            type="md"
            color="primary"
            classes="text-center text-black font-normal text-base leading-normal text-center mt-4 mb-4"
          />

          <div className="container mx-auto flex flex-wrap items-start justify-center pt-10 gap-8">
            <div className="flex lg:flex-col sm:flex-col md:flex-col xs:flex-col">
              <div className="flex gap-16 sm:flex-col xs:flex-col sm:justify-center sm:items-center xs:justify-center xs:items-center">
                {!isLoading ? (
                  <div>
                    {data &&
                      data.map(
                        (
                          item: {
                            _id: any;
                            main_image: string | undefined;
                            title:
                              | boolean
                              | React.ReactChild
                              | React.ReactFragment
                              | React.ReactPortal
                              | null
                              | undefined;
                            createdAt: moment.MomentInput;
                          },
                          i: React.Key | null | undefined
                        ) => (
                          <div key={i} className="pb-20">
                            {/* <Link href="/blogs/[blog]" as={`/blogs/${item._id}`}> */}
                            <Link href="/blogs/" as={`/blogs/${item._id}`}>
                              <img
                                src={item.main_image}
                                alt="woman smiling"
                                className="w-[100%] h-auto"
                              />
                            </Link>

                            <h2 className="text-xl font-semibold leading-5 mt-8 text-gray-800">
                              {item.title}
                            </h2>
                            <div className="mt-6 flex items-center">
                              {/* <Link href="/blogs/[blog]" as={`/blogs/${item._id}`} className="flex"> */}
                              <Link href="/blogs/[blog" as={`/blogs/${item._id}`} className="flex">
                                <p className="pr-3 text-base font-medium leading-4 underline text-gray-800">
                                  5 min read
                                </p>
                                <svg
                                  width={16}
                                  height={10}
                                  viewBox="0 0 16 10"
                                  fill="none"
                                  xmlns="http://www.w3.org/2000/svg"
                                >
                                  <path
                                    d="M1 5H15"
                                    stroke="#1F2937"
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                  />
                                  <path
                                    d="M11 9L15 5"
                                    stroke="#1F2937"
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                  />
                                  <path
                                    d="M11 1L15 5"
                                    stroke="#1F2937"
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                  />
                                </svg>
                              </Link>
                            </div>
                            <p className="text-base mt-4 italic font-italic leading-4 text-gray-600">
                              {moment(item.createdAt).format('ll')}
                            </p>
                          </div>
                        )
                      )}
                  </div>
                ) : (
                  <div className="container max-w-6xl mt-12 p-6 mx-auto space-y-6 sm:space-y-12">
                    <Loader />
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
        <div className="div">
          <Footer />
        </div>
      </main>
    </div>
  );
};

export default Home;
