/* eslint-disable prettier/prettier */
/* eslint-disable import/no-named-as-default */
/* eslint-disable prettier/prettier */
import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Heading from '../../shared/ui/Heading/Heading';
import Header from '../../shared/ui/Header/Header';
import Footer from '../../shared/ui/Footer/Footer';
import Image11 from '../../../public/image11.png';
import Image12 from '../../../public/image12.png';
import Image13 from '../../../public/image13.png';
import Image21 from '../../../public/image21.png';
import Image22 from '../../../public/image22.png';
import Image23 from '../../../public/image23.png';
import CTAImage from '../../../public/CTA.png';
import Empower from '../Components/Empower';
import VideoThumbnail from '../Components/VideoThumbnail';
import Customers from '../Components/Customers';
import Fetured from '../Components/Fetured';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>DAMS</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="theme-color" content="#151515" />
    </Head>
    <main>
      <div className="navbar relative z-10">
        <Header />
      </div>

      <div className="container bg-transparent px-2 sm:px-4 w-full pt-12">
        <div className="w-[89%] flex flex-wrap  justify-between mx-auto">
          <div className="w-full flex flex-col justify-center items-start py-20">
            <Heading
              title="Invest In DAMS Products"
              type="newxl"
              color="primary"
              classes="text-bordercolor font-semibold"
            />
            <Heading
              title="Trusted by Millions of People. Start investing today."
              type="sm"
              color="primary"
              classes="text-black font-normal mb-10"
            />

            <Link
              href="/auth/signin/"
              className="text-white bg-bordercolor focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-md px-7 py-3.5 text-center mr-3 md:mr-0 transform transition duration-300 hover:scale-110"
            >
              Create free account
            </Link>
          </div>

          <div className="w-full flex flex-col justify-center items-center py-20">
            <div className="flex justify-between w-[100%]">
              <Link href="/products/loans/">
                <div className="px-20 flex flex-col justify-center items-start w-[310px] h-[260px] bg-white rounded-2xl shadow-lg border-solid border-gray-300 border-2 transform transition duration-300 hover:scale-105">
                  <Image src={Image11} className="card-image w-[100px]" alt="Image" />
                  <Heading title="Loans" type="xl" color="primary" classes="text-black font-bold" />
                </div>
              </Link>

              <Link href="/products/piggybank/">
                <div className="px-20 flex flex-col justify-center items-start w-[310px] h-[260px] bg-white rounded-2xl shadow-lg border-solid border-gray-300 border-2 transform transition duration-300 hover:scale-105">
                  <Image src={Image12} className="card-image w-[100px]" alt="Image" />
                  <Heading
                    title="Piggy Bank"
                    type="xl"
                    color="primary"
                    classes="text-black font-bold"
                  />
                </div>
              </Link>

              <Link href="/products/safelock/">
                <div className="px-20 flex flex-col justify-center items-start w-[310px] h-[260px] bg-white rounded-2xl shadow-lg border-solid border-gray-300 border-2 transform transition duration-300 hover:scale-105">
                  <Image src={Image13} className="card-image w-[100px]" alt="Image" />
                  <Heading
                    title="Safelock"
                    type="xl"
                    color="primary"
                    classes="text-black font-bold"
                  />
                </div>
              </Link>
            </div>

            <div className="flex justify-between w-[100%] mt-[100px]">
              <Link href="/products/target-saving/">
                <div className="px-20 flex flex-col justify-center items-start w-[310px] h-[260px] bg-white rounded-2xl shadow-lg border-solid border-gray-300 border-2 transform transition duration-300 hover:scale-105">
                  <Image src={Image21} className="card-image w-[100px]" alt="Image" />
                  <div className="w-[50%] pt-5">
                    <Heading
                      title="Target Saving"
                      type="xl"
                      color="primary"
                      classes="text-black font-bold"
                    />
                  </div>
                </div>
              </Link>

              <Link href="/products/invest/">
                <div className="px-20 flex flex-col justify-center items-start w-[310px] h-[260px] bg-white rounded-2xl shadow-lg border-solid border-gray-300 border-2 transform transition duration-300 hover:scale-105">
                  <Image src={Image22} className="card-image w-[100px]" alt="Image" />
                  <div className="w-[50%] pt-5">
                    <Heading
                      title="Invest"
                      type="xl"
                      color="primary"
                      classes="text-black font-bold"
                    />
                  </div>
                </div>
              </Link>

              <Link href="/products/flexnaira/">
                <div className="px-20 flex flex-col justify-center items-start w-[310px] h-[260px] bg-white rounded-2xl shadow-lg border-solid border-gray-300 border-2 transform transition duration-300 hover:scale-105">
                  <Image src={Image23} className="card-image w-[100px]" alt="Image" />
                  <div className="w-[50%] pt-5">
                    <Heading
                      title="Flex Naira"
                      type="xl"
                      color="primary"
                      classes="text-black font-bold"
                    />
                  </div>
                </div>
              </Link>
            </div>
          </div>

          <div className="w-full flex flex-col justify-center items-center py-20">
            <div className="mx-auto container py-12">
              <div className="w-full flex justify-center">
                <div className="w-full md:w-11/12 xl:w-10/12 bg-gradient-to-r from-indigo-500 to-indigo-700 md:py-8 md:px-8 px-5 py-4 xl:px-12 xl:py-16">
                  <div className="flex flex-wrap items-center md:flex-row flex-col-reverse">
                    <div className="md:w-2/3 w-full pb-6 md:pb-0 md:pr-6 flex-col md:block flex items-center justify-center md:pt-0 pt-4">
                      <div>
                        <Heading
                          title="Become a member and start investment"
                          type="newxl"
                          color="primary"
                          classes="text-[#fff] font-semibold mb-14"
                        />
                      </div>

                      <Link
                        href="/auth/signin/"
                        className="lg:mt-8 py-3 lg:py-4 px-4 lg:px-8 bg-white font-bold text-indigo-700 rounded-lg text-sm lg:text-lg xl:text-xl hover:bg-opacity-90 focus:ring-2 focus:ring-offset-2 focus:ring-white focus:outline-none"
                      >
                        Create free account
                      </Link>
                    </div>
                    <div className="md:w-1/3 w-2/3">
                      <Image src={CTAImage} alt="cartoon avatars" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="div">
        <Empower />
      </div>

      <div className="div mt-[144px]">
        <VideoThumbnail />
      </div>
      <div className="div mt-[144px]">
        <Customers />
      </div>
      <div className="div mt-[144px]">
        <Fetured />
      </div>

      <div className="div">
        <Footer />
      </div>
    </main>
  </div>
);

export default Home;
