/* eslint-disable prettier/prettier */
import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Heading from '../../shared/ui/Heading/Heading';
import Header from '../../shared/ui/Header/Header';
import Footer from '../../shared/ui/Footer/Footer';
import InvestmentImage from '../../../public/investment.png';
import Empower from '../Components/Empower';
import VideoThumbnail from '../Components/VideoThumbnail';
import Customers from '../Components/Customers';
import Fetured from '../Components/Fetured';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>DAMS</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="theme-color" content="#151515" />
    </Head>
    <main>
      <div className="navbar relative z-10">
        <Header />
      </div>

      <div className="container bg-transparent px-2 sm:px-4 w-full pt-10">
        <div className="w-[89%] mx-auto">
          <div className="w-full flex flex-col justify-center items-start py-20">
            <Heading
              title="Invest In DAMS Investment Plans"
              type="newxl"
              color="primary"
              classes="text-bordercolor font-semibold"
            />
            <Heading
              title="Trusted by Millions of People. Start investing today."
              type="sm"
              color="primary"
              classes="text-black font-normal mb-10"
            />

            <Link
              href="/auth/signin/"
              className="text-white bg-bordercolor focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-md px-7 py-3.5 text-center mr-3 md:mr-0 transform transition duration-300 hover:scale-110"
            >
              Create free account
            </Link>
          </div>

          <div className="hero flex flex-wrap justify-between bg-bordercolor rounded-lg">
            <div className="flex flex-col justify-center w-[50%] px-8">
              <Heading
                title="Invest In DAMS Investment Plans"
                type="newxl"
                color="primary"
                classes="text-white font-semibold mr-10"
              />
              <Heading
                title="A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future."
                type="sm"
                color="primary"
                classes="text-white font-normal mr-10 mt-4"
              />
            </div>
            <div className="w-[50%]">
              <Image
                src={InvestmentImage}
                className="card-image w-[100%] rounded-r-lg"
                alt="Image"
              />
            </div>
          </div>

          <div className="about flex justify-start my-16 px-4">
            <div className="w-[75%] flex flex-col justify-center">
              <Heading
                title="Invest In DAMS DAMS Investment Plans"
                type="xl"
                color="primary"
                classes="text-bordercolor font-semibold pb-4"
              />
              <Heading
                title="A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future."
                type="sm"
                color="primary"
                classes="text-black font-normal pb-4"
              />
              <Heading
                title="A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future."
                type="sm"
                color="primary"
                classes="text-black font-normal pb-4"
              />
              <Heading
                title="A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future. A powerful money app, inbuilt savings account, and a debit card that helps you take full charge of your money & create wealth for your future."
                type="sm"
                color="primary"
                classes="text-black font-normal pb-4"
              />
            </div>
          </div>

          <div className="dark:bg-gray-900 my-16 rounded-lg">
            <div className="pb-20">
              <div className="mx-auto bg-gradient-to-l from-indigo-600 to-indigo-700 h-96 rounded-lg">
                <div className="mx-auto container w-full flex flex-col justify-center items-center">
                  <div className="flex justify-center items-center flex-col">
                    <div className="mt-20">
                      <Heading
                        title="By the numbers"
                        type="newxxl"
                        color="primary"
                        classes="text-white font-black leading-10 font-bold"
                      />
                    </div>
                    <div className="mt-6 mx-2 md:mx-0 text-center">
                      <Heading
                        title="5 years, consistent quality and you get results. No matter what"
                        type="md"
                        color="primary"
                        classes="text-white font-black leading-6 font-normal"
                      />
                    </div>
                  </div>
                </div>
              </div>

              <div className="mx-auto container md:-mt-28 -mt-20 flex justify-center items-center">
                <div className="grid lg:grid-cols-4 md:grid-cols-2 grid-cols-2 gap-x-2 gap-y-2 lg:gap-x-6 md:gap-x-6 md:gap-y-6 md:gap-y-6">
                  <div className="flex justify-center flex-col items-center w-36 h-36 md:w-44 md:h-48 lg:w-56 lg:h-56 bg-white shadow rounded-2xl">
                    <Heading
                      title="40+"
                      type="newxl"
                      color="primary"
                      classes="text-bordercolor font-black leading-6 font-extrabold"
                    />
                    <Heading
                      title="Happy Clients"
                      type="xl"
                      color="primary"
                      classes="text-black font-normal mt-4 text-sm md:text-base lg:text-lg leading-none text-center"
                    />
                  </div>
                  <div className="flex justify-center flex-col items-center w-36 h-36 md:w-44 md:h-48 lg:w-56 lg:h-56 bg-white shadow rounded-2xl">
                    <Heading
                      title="540+"
                      type="newxl"
                      color="primary"
                      classes="text-bordercolor font-black leading-6 font-extrabold"
                    />
                    <Heading
                      title="Projects Completed"
                      type="xl"
                      color="primary"
                      classes="text-black font-normal mt-4 text-sm md:text-base lg:text-lg leading-none text-center"
                    />
                  </div>
                  <div className="flex justify-center flex-col items-center w-36 h-36 md:w-44 md:h-48 lg:w-56 lg:h-56 bg-white shadow rounded-2xl">
                    <Heading
                      title="300+"
                      type="newxl"
                      color="primary"
                      classes="text-bordercolor font-black leading-6 font-extrabold"
                    />
                    <Heading
                      title="Dedicated Members"
                      type="xl"
                      color="primary"
                      classes="text-black font-normal mt-4 text-sm md:text-base lg:text-lg leading-none text-center"
                    />
                  </div>
                  <div className="flex justify-center flex-col items-center w-36 h-36 md:w-44 md:h-48 lg:w-56 lg:h-56 bg-white shadow rounded-2xl">
                    <Heading
                      title="25+"
                      type="newxl"
                      color="primary"
                      classes="text-bordercolor font-black leading-6 font-extrabold"
                    />
                    <Heading
                      title="Awards Won"
                      type="xl"
                      color="primary"
                      classes="text-black font-normal mt-4 text-sm md:text-base lg:text-lg leading-none text-center"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="div">
        <Empower />
      </div>

      <div className="div mt-[144px]">
        <VideoThumbnail />
      </div>
      <div className="div mt-[144px]">
        <Customers />
      </div>
      <div className="div mt-[144px]">
        <Fetured />
      </div>

      <div className="div">
        <Footer />
      </div>
    </main>
  </div>
);

export default Home;
