/* eslint-disable prettier/prettier */
import React from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Heading from '../../shared/ui/Heading/Heading';
import Header from '../../shared/ui/Header/Header';
import Footer from '../../shared/ui/Footer/Footer';
import About1 from '../../../public/about1.png';
import About2 from '../../../public/about2.png';
import About3 from '../../../public/about3.png';
import About4 from '../../../public/about4.svg';
import About5 from '../../../public/about5.svg';
import About6 from '../../../public/about6.svg';
import About7 from '../../../public/about7.svg';
import About8 from '../../../public/about8.svg';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>DAMS</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="theme-color" content="#151515" />
    </Head>
    <main>
      <div className="navbar relative z-10">
        <Header />
      </div>

      <div className="2xl:container 2xl:mx-auto lg:py-16 lg:px-20 md:py-12 md:px-6 py-9 px-4">
        <Heading
          title="About"
          type="md"
          color="primary"
          classes="text-black font-normal dark:text-indigo-500 hover:text-indigo-800 cursor-pointer pb-2"
        />

        <div className="flex lg:flex-row flex-col lg:gap-8 sm:gap-10 gap-12">
          <div className="w-full lg:w-6/12">
            <Heading
              title="We are here to make great design accessible and delightfull for everyone"
              type="xl"
              color="primary"
              classes="text-bordercolor font-bold cursor-pointer pb-2"
            />

            <Heading
              title="It is a long established fact that a reader will be distracted by the readable content
              of a page when looking at its layout. The point of using Lorem Ipsum.In the first
              place we have granted to God, and by this our present charter confirmed for us and our
              heirs forever that the English Church shall be free, and shall have her rights entire,"
              type="sm"
              color="primary"
              classes="text-black font-normal text-base mt-6"
            />
          </div>
          <div className="w-full lg:w-6/12">
            <Image
              className="lg:block hidden w-full"
              src={About1}
              alt="people discussing on board"
            />
            <Image
              className="lg:hidden sm:block hidden w-full"
              src={About2}
              alt="people discussing on board"
            />
            <Image
              className="sm:hidden block w-full"
              src={About3}
              alt="people discussing on board"
            />
          </div>
        </div>

        <div className="relative mt-24">
          <div className="grid sm:grid-cols-3 grid-cols-2 sm:gap-8 gap-4">
            <div className="z-20 w-12 h-12 bg-gray-800 rounded-full flex justify-center items-center">
              <Image src={About4} alt="flag" className="w-full" />
            </div>

            <Image className="z-20 w-[48px] h-[48px]" src={About5} alt="note" />

            <Image className="z-20 sm:block hidden w-[48px] h-[48px]" src={About6} alt="users" />
          </div>
          <hr className="z-10 absolute top-2/4 w-full bg-gray-200" />
        </div>
        <div className="grid sm:grid-cols-3 grid-cols-2 sm:gap-8 gap-4">
          <div>
            <Heading
              title="Founded"
              type="xl"
              color="primary"
              classes="text-bordercolor font-semibold text-base mt-6"
            />
            <Heading
              title="It is a long established fact that a reader will be distracted by the readable content
              of a page when looking at its layout."
              type="sm"
              color="primary"
              classes="text-black font-normal text-base text-base mt-6"
            />
          </div>
          <div>
            <Heading
              title="50M montly enrichments"
              type="xl"
              color="primary"
              classes="text-bordercolor font-semibold text-base mt-6"
            />
            <Heading
              title="It is a long established fact that a reader will be distracted by the readable content
              of a page when looking at its layout."
              type="sm"
              color="primary"
              classes="text-black font-normal text-base text-base mt-6"
            />
          </div>
          <div className="sm:block hidden">
            <Heading
              title="400k User"
              type="xl"
              color="primary"
              classes="text-bordercolor font-semibold text-base mt-6"
            />
            <Heading
              title="It is a long established fact that a reader will be distracted by the readable content
              of a page when looking at its layout."
              type="sm"
              color="primary"
              classes="text-black font-normal text-base text-base mt-6"
            />
          </div>
        </div>
        <div className="sm:hidden block relative mt-8">
          <div className="grid sm:grid-cols-3 grid-cols-2 sm:gap-8 gap-4">
            <Image src={About7} alt="user" className="w-full" />
          </div>
          <hr className="z-10 absolute top-2/4 w-full bg-gray-200" />
        </div>
        <div className="sm:hidden grid sm:grid-cols-3 grid-cols-2 sm:gap-8 gap-4">
          <div>
            <Heading
              title="400k User"
              type="xl"
              color="primary"
              classes="text-bordercolor font-semibold text-base mt-6"
            />
            <Heading
              title="It is a long established fact that a reader will be distracted by the readable content
              of a page when looking at its layout."
              type="sm"
              color="primary"
              classes="text-black font-normal text-base text-base mt-6"
            />
          </div>
        </div>

        <div className="flex lg:flex-row flex-col md:gap-14 gap-16 justify-between lg:mt-20 mt-16">
          <div className="w-full lg:w-6/12">
            <Heading
              title="Our Mission"
              type="xl"
              color="primary"
              classes="text-bordercolor font-bold text-base mt-6"
            />
            <Heading
              title="It is a long established fact that a reader will be distracted by the readable content
              of a page when looking at its layout. The point of using Lorem Ipsum.In the first
              place we have granted to God, and by this our present charter confirmed for us and our
              heirs forever that the English Church shall be free, and shall have her rights entire,
              and her liberties inviolate; and we will that it be thus observed; which is apparent
              from"
              type="sm"
              color="primary"
              classes="text-black font-normal text-base text-base mt-6"
            />
            <Heading
              title="It is a long established fact that a reader will be distracted by the readable content
              of a page when looking at its layout. The point of using Lorem Ipsum.In the first
              place we have granted to God, and by this our present charter confirmed for us and our
              heirs forever that the English Church shall be free, and shall have her rights entire,
              and her liberties inviolate; and we will that it be thus observed; which is apparent
              from"
              type="sm"
              color="primary"
              classes="text-black font-normal text-base text-base mt-6"
            />
          </div>
          <div className="w-full lg:w-6/12">
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-1 lg:gap-12 gap-10">
              <div className="flex p-4 shadow-md">
                <div className="mr-6 mt-6">
                  <Image className="mr-6 w-full" src={About6} alt="team card" />
                </div>
                <div className="">
                  <Heading
                    title="Team"
                    type="lg"
                    color="primary"
                    classes="text-bordercolor font-semibold text-base mt-6"
                  />
                  <Heading
                    title="It is a long established fact that a reader will be distracted by the readable
                    content of a page when looking at its layout."
                    type="sm"
                    color="primary"
                    classes="text-black font-normal text-base text-base mt-6"
                  />
                </div>
              </div>

              <div className="flex p-4 shadow-md">
                <div className="mr-6 mt-6">
                  <Image src={About7} alt="board card" className="w-[48px] h-[48px]" />
                </div>
                <div className="">
                  <Heading
                    title="Board"
                    type="lg"
                    color="primary"
                    classes="text-bordercolor font-semibold text-base mt-6"
                  />
                  <Heading
                    title="It is a long established fact that a reader will be distracted by the readable
                    content of a page when looking at its layout."
                    type="sm"
                    color="primary"
                    classes="text-black font-normal text-base text-base mt-6"
                  />
                </div>
              </div>

              <div className="flex p-4 shadow-md">
                <div className="mr-6 mt-6">
                  <Image src={About8} alt="press card" className="w-[48px] h-[48px]" />
                </div>
                <div className="">
                  <Heading
                    title="Press"
                    type="lg"
                    color="primary"
                    classes="text-bordercolor font-semibold text-base mt-6"
                  />
                  <Heading
                    title="It is a long established fact that a reader will be distracted by the readable
                    content of a page when looking at its layout."
                    type="sm"
                    color="primary"
                    classes="text-black font-normal text-base text-base mt-6"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="div">
        <Footer />
      </div>
    </main>
  </div>
);

export default Home;
