/* eslint-disable prettier/prettier */
/* eslint-disable no-else-return */
/* eslint-disable react/no-unknown-property */
/* eslint-disable react/button-has-type */
/* eslint-disable prettier/prettier */
import React, { useState, useEffect } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Heading from '../../shared/ui/Heading/Heading';
import Accordian from '../../shared/ui/Accordion/Accordian';
import Header from '../../shared/ui/Header/Header';
import { Loader } from '../../shared/ui/Loader/Loader';
import Footer from '../../shared/ui/Footer/Footer';
import FaqBackground from '../../../public/faq-bg.png';
import { useGetAllFaqMutation } from '../../shared/api/faqApi/faqApi';

const Home: NextPage = () => {
  const [page] = useState(1);
  const [limit] = useState(10);

  const [getAllFaq, { data, isLoading }] = useGetAllFaqMutation();

  const GetData = async () => {
    try {
      await getAllFaq({
        page,
        limit,
      });
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    GetData();
  }, []);

  if (isLoading) {
    return (
      <div className="container max-w-6xl mt-12 p-6 mx-auto space-y-6 sm:space-y-12">
        <Loader />
      </div>
    );
  }

  return (
    <div>
      <Head>
        <title>DAMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content="#151515" />
      </Head>
      <main>
        <div className="navbar relative z-10">
          <Header />
        </div>
        <div className="mt-10">
          <Image
            src={FaqBackground}
            alt="blue pattern background"
            className="absolute w-full h-64 md:h-96 object-center object-fit z-0"
          />

          <div className="relative flex flex-col items-center justify-center sm:px-0 px-6 z-20 pb-32">
            <div className="md:py-36 py-20">
              <Heading
                title="Frequently asked questions"
                type="newxl"
                color="primary"
                classes="text-[#fff] font-semibold cursor-pointer pb-2"
              />
            </div>

            <div className="lg:w-1/2 md:w-8/12 sm:w-9/12 w-full">
              {data &&
                data.map(
                  (item: { title: string; description: any }, i: React.Key | null | undefined) => (
                    <div className="bg-white shadow rounded p-8 m-4 cursor-pointer" key={i}>
                      <Accordian
                        title={item.title}
                        content={item.description}
                        footer=""
                        classes="cursor-pointer"
                        titleType="heading"
                        descriptionType="lg"
                      />
                    </div>
                  )
                )}
            </div>
          </div>
        </div>
        <div className="div">
          <Footer />
        </div>
      </main>
    </div>
  );
};

export default Home;
